print('number 1')
print("")
local number1 = io.read()
print("")
print("+ - / *")
print("")
local h = io.read()
print("")
print("number 2")
print("")
local number2 = io.read()
if h == "+" then
    print("")
    print("output:")
    print("")
    print(number1 + number2)
elseif h == "-" then
    print("")
    print("output:")
    print("")
    print(number1 - number2)
elseif h == "/" then
    print("")
    print("output:")
    print("")
    print(number1 / number2)
elseif h == "*" then
    print("")
    print("output:")
    print("")
    print(number1 * number2)
else
    print("")
    error("please enter something valid")
end